### ISSUE TITLE
A VideoCapturer must provide at least one supported VideoFormat

### ISSUE THREAD

**Issue by ImAliveAndThatIsNice** [PriceFallin/cordova-plugin-twilio-video#4]
I am getting the following erro but only in a specific device (smart glasses):

 java.lang.IllegalStateException: A VideoCapturer must provide at least one supported VideoFormat
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
at android.app.ActivityThread.-wrap11(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5417)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
I am getting the following error on smart glasses:

Caused by: java.lang.IllegalStateException: A VideoCapturer must provide at least one supported VideoFormat
at com.twilio.video.Preconditions.checkState(Preconditions.java:453)
at com.twilio.video.LocalVideoTrack.create(LocalVideoTrack.java:70)
at com.twilio.video.LocalVideoTrack.create(LocalVideoTrack.java:44)
at cordova.plugin.twilio.video.ConversationActivity.createAudioAndVideoTracks(ConversationActivity.java:264)
at cordova.plugin.twilio.video.ConversationActivity.onCreate(ConversationActivity.java:136)
at android.app.Activity.performCreate(Activity.java:6275)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)

**Comment by ImAliveAndThatIsNice** [comment]
Hey PriceFallin,

Thanks for your response. I found out that the error was caused by trying to use a camera that the device doesn't have (it only have one camera).
